#!/bin/bash

# Valentine's App - Audio File Auto-Detector
# Run this script whenever you add new audio files to automatically update index.html

echo "🎵 Scanning audio folders for files..."

# Function to scan a folder and generate JavaScript array
generate_file_list() {
    local folder=$1
    local category=$2
    local files=()

    # Find all audio files in the folder
    while IFS= read -r file; do
        # Get just the filename (relative to project root)
        relative_path="audio/$folder/$(basename "$file")"
        files+=("'$relative_path'")
    done < <(find "audio/$folder" -type f \( -name "*.m4a" -o -name "*.mp3" -o -name "*.wav" -o -name "*.aac" \) 2>/dev/null | sort)

    # Join array elements with comma and newline
    if [ ${#files[@]} -eq 0 ]; then
        echo "                // No audio files found yet - add some .m4a files to this folder!"
    else
        printf "                %s" "${files[0]}"
        for ((i=1; i<${#files[@]}; i++)); do
            printf ",\n                %s" "${files[i]}"
        done
    fi
}

# Generate the new audioFiles configuration
cat > /tmp/audio_config.js << 'EOF'
        // Audio files configuration - AUTO-GENERATED by update-audio-files.sh
        // DO NOT EDIT MANUALLY - Run ./update-audio-files.sh to update this section
        const audioFiles = {
            hype: [
EOF

echo "$(generate_file_list "hype-monstermanny-up" "hype")" >> /tmp/audio_config.js

cat >> /tmp/audio_config.js << 'EOF'

            ],
            hug: [
EOF

echo "$(generate_file_list "i-need-a-hug" "hug")" >> /tmp/audio_config.js

cat >> /tmp/audio_config.js << 'EOF'

            ],
            jokes: [
EOF

echo "$(generate_file_list "ujjal-dad-ar-jokes" "jokes")" >> /tmp/audio_config.js

cat >> /tmp/audio_config.js << 'EOF'

            ],
            kidda: [
EOF

echo "$(generate_file_list "kidda-lovely-dovely" "kidda")" >> /tmp/audio_config.js

cat >> /tmp/audio_config.js << 'EOF'

            ]
        };
EOF

# Now update the index.html file
# We'll replace everything between the audioFiles declaration and the closing brace

# Create backup
cp index.html index.html.backup

# Use sed to replace the audioFiles section
# This is a bit tricky - we'll use a multi-line approach
python3 << 'PYTHON_SCRIPT'
import re

# Read the current index.html
with open('index.html', 'r') as f:
    content = f.read()

# Read the new audio config
with open('/tmp/audio_config.js', 'r') as f:
    new_config = f.read()

# Replace the audioFiles section
# Pattern: from "const audioFiles = {" to the closing "};" before categoryIcons
pattern = r'([ \t]*// Audio files configuration.*?\n[ \t]*const audioFiles = \{).*?(\n[ \t]*\};)'

replacement = new_config.rstrip() + r'\2'

# Perform the replacement
new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

# Write back
with open('index.html', 'w') as f:
    f.write(new_content)

print("✅ index.html updated successfully!")
PYTHON_SCRIPT

# Summary
echo ""
echo "📊 Summary:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
for folder in "hype-monstermanny-up" "i-need-a-hug" "ujjal-dad-ar-jokes" "kidda-lovely-dovely"; do
    count=$(find "audio/$folder" -type f \( -name "*.m4a" -o -name "*.mp3" -o -name "*.wav" -o -name "*.aac" \) 2>/dev/null | wc -l)
    echo "  $folder: $count audio files"
done
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Done! Your index.html has been updated with all audio files."
echo "💡 Backup saved as: index.html.backup"
echo ""
echo "🎁 Just open index.html in your browser to test!"
